import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { SessionProvider } from 'next-auth/react';
import { TRPCReactProvider } from '@/trpc/client';
import { Toaster } from 'sonner';

const inter = Inter({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Landix',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TRPCReactProvider>
      <html lang="en">
        <body className={`${inter.className} antialiased`}>
          <SessionProvider>{children}</SessionProvider>
          <Toaster position="bottom-right" richColors />
        </body>
      </html>
    </TRPCReactProvider>
  );
}
